service: sqs-example

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    QUEUE_URL: "hello there"

functions:
  pushToQueue:
    handler: handler.pushToQueue
    events:
      - http:
          path: pushToQueue
          method: post

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 86400

