service: sqs-example

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    QUEUE_URL:
      Ref: SQSQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:sendMessage"
      Resource:
        Fn::GetAtt: [SQSQueue, Arn]

functions:
  pushToQueue:
    handler: handler.pushToQueue
    events:
      - http:
          path: pushToQueue
          method: post
  queueProcessMessage:
    handler: handler.processQueueMessages
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSQueue, Arn]
  

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 86400

