service: sqs-example

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        MessageRetentionPeriod: 86400